// Modbus serial comunication
#define SERIAL_STREAM Serial2
#define SERIAL_STREAM_SPEED 115200

// MODBUS ID
#define MODBUS_ID 0x01

/* ADDRESSES of TRACER_AN SERIES */
// Read Input Register (0x04) - RATED DATA
#define MODBUS_ADDRESS_PV_RATED_VOLTAGE                 0x3000
#define MODBUS_ADDRESS_PV_RATED_CURRENT                 0x3001
#define MODBUS_ADDRESS_PV_RATED_POWER                   0x3002 // 2 addresses
#define MODBUS_ADDRESS_BATTERY_RATED_VOLTAGE            0x3004
#define MODBUS_ADDRESS_BATTERY_RATED_CURRENT            0x3005
#define MODBUS_ADDRESS_BATTERY_RATED_POWER              0x3006 // 2 addresses
#define MODBUS_ADDRESS_CHARGING_MODE                    0x3008
#define MODBUS_ADDRESS_LOAD_RATED_CURRENT               0x300E

// Read Input Register (0x04) - REAL TIME DATA
#define MODBUS_ADDRESS_PV_VOLTAGE                       0x3100
#define MODBUS_ADDRESS_PV_CURRENT                       0x3101
#define MODBUS_ADDRESS_PV_POWER                         0x3102 // 2 addresses
#define MODBUS_ADDRESS_BATTERY_CURRENT_VOLTAGE          0x3104
#define MODBUS_ADDRESS_BATTERY_CHARGE_CURRENT           0x3105
#define MODBUS_ADDRESS_BATTERY_POWER                    0x3106 // 2 addresses
#define MODBUS_ADDRESS_LOAD_VOLTAGE                     0x310C
#define MODBUS_ADDRESS_LOAD_CURRENT                     0x310D
#define MODBUS_ADDRESS_LOAD_POWER                       0x310E // 2 addresses
#define MODBUS_ADDRESS_BATTERY_TEMP                     0x3110
#define MODBUS_ADDRESS_CONTROLLER_TEMP                  0x3111
#define MODBUS_ADDRESS_BATTERY_SOC                      0x311A
#define MODBUS_ADDRESS_BATTERY_REMOTE_TEMP              0x311B
#define MODBUS_ADDRESS_REAL_RATED_VOLTAGE               0x311D

// Read Input Register (0x04) - REAL TIME STATUS
#define MODBUS_ADDRESS_BATTERY_STATUS                   0x3200
#define MODBUS_ADDRESS_CHARGING_EQUIPMENT_STATUS        0x3201
#define MODBUS_ADDRESS_DISCHARGING_EQUIPMENT_STATUS     0x3202

// Read Input Register (0x04) - STATISTICS
#define MODBUS_ADDRESS_STAT_MAX_PV_VOLTAGE_TODAY        0x3300
#define MODBUS_ADDRESS_STAT_MIN_PV_VOLTAGE_TODAY        0x3301
#define MODBUS_ADDRESS_STAT_MAX_BATTERY_VOLTAGE_TODAY   0x3302
#define MODBUS_ADDRESS_STAT_MIN_BATTERY_VOLTAGE_TODAY   0x3303
#define MODBUS_ADDRESS_STAT_CONSUMED_ENERGY_TODAY       0x3304 // 2 addresses
#define MODBUS_ADDRESS_STAT_CONSUMED_ENERGY_MONTHLY     0x3306 // 2 addresses
#define MODBUS_ADDRESS_STAT_CONSUMED_ENERGY_ANNUALY     0x3308 // 2 addresses
#define MODBUS_ADDRESS_STAT_CONSUMED_ENERGY_TOTAL       0x330A // 2 addresses
#define MODBUS_ADDRESS_STAT_GENERATED_ENERGY_TODAY      0x330C // 2 addresses
#define MODBUS_ADDRESS_STAT_GENERATED_ENERGY_MONTH      0x330E // 2 addresses
#define MODBUS_ADDRESS_STAT_GENERATED_ENERGY_YEAR       0x3310 // 2 addresses
#define MODBUS_ADDRESS_STAT_GENERATED_ENERGY_TOTAL      0x3312 // 2 addresses
#define MODBUS_ADDRESS_STAT_BATTERY_VOLTAGE_OVERALL     0x331A
#define MODBUS_ADDRESS_STAT_BATTERY_CURRENT_OVERALL     0x331B // 2 addresses

/* Read Holding Register (0x03), Write Multiple Holding (0x10) - SETTINGS */
#define MODBUS_ADDRESS_BATTERY_TYPE                     0x9000
#define MODBUS_ADDRESS_BATTERY_CAPACITY                 0x9001
#define MODBUS_ADDRESS_BATTERY_TEMP_COEFF               0x9002
#define MODBUS_ADDRESS_HIGH_VOLTAGE_DISCONNECT          0x9003
#define MODBUS_ADDRESS_CHARGING_LIMIT_VOLTAGE           0x9004
#define MODBUS_ADDRESS_OVER_VOLTAGE_RECONNECT           0x9005
#define MODBUS_ADDRESS_EQUALIZATION_VOLTAGE             0x9006
#define MODBUS_ADDRESS_BOOST_VOLTAGE                    0x9007
#define MODBUS_ADDRESS_FLOAT_VOLTAGE                    0x9008
#define MODBUS_ADDRESS_BOOST_RECONNECT_VOLTAGE          0x9009
#define MODBUS_ADDRESS_LOW_VOLTAGE_RECONNECT            0x900A
#define MODBUS_ADDRESS_UNDER_VOLTAGE_RECOVER            0x900B
#define MODBUS_ADDRESS_UNDER_VOLTAGE_WARNING            0x900C
#define MODBUS_ADDRESS_LOW_VOLTAGE_DISCONNECT           0x900D
#define MODBUS_ADDRESS_DISCHARGING_LIMIT_VOLTAGE        0x900E

#define MODBUS_ADDRESS_REALTIME_CLOCK_1                 0x9013
#define MODBUS_ADDRESS_REALTIME_CLOCK_2                 0x9014
#define MODBUS_ADDRESS_REALTIME_CLOCK_3                 0x9015
#define MODBUS_ADDRESS_BATTERY_TEMP_WARN_UPPER_LIMIT    0x9017
#define MODBUS_ADDRESS_BATTERY_TEMP_WARN_LOWER_LIMIT    0x9018
#define MODBUS_ADDRESS_CONTROLLER_TEMP_WARN_UPPER_LIMIT 0x9019
#define MODBUS_ADDRESS_CONTROLLER_TEMP_WARN_RECOVER     0x901A

// finish 901E - 9070
#define MODBUS_ADDRESS_CONTROLLER_SUPPLY                0x9066
#define MODBUS_ADDRESS_BATTERY_RATED_VOLTAGE_CODE       0x9067
// #define MODBUS_ADDRESS_EQUALIZE_DURATION                0x906B
// #define MODBUS_ADDRESS_BOOST_DURATION                   0x906C
// #define MODBUS_ADDRESS_CHARGING_MODE                    0x9070

// Read Coils (0x01), Write Coils (0x05) - SETTINGS
#define MODBUS_ADDRESS_BATTERY_CHARGE_ONOFF             0x0000
#define MODBUS_ADDRESS_LOAD_AUTOMATIC_ONOFF             0x0001
#define MODBUS_ADDRESS_LOAD_MANUAL_ONOFF                0x0002
#define MODBUS_ADDRESS_LOAD_DEFAULT_MODE                0x0003
#define MODBUS_ADDRESS_LOAD_TEST_MODE                   0x0005
#define MODBUS_ADDRESS_LOAD_FORCE_ONOFF                 0x0006
#define MODBUS_ADDRESS_RESTORE_SYSTEM_DEFAULT           0x0013
#define MODBUS_ADDRESS_CLEAR_STAT                       0x0006

// Read Discrete Input (0x02) - DISCRETE VALUE
#define MODBUS_ADDRESS_OVER_TEMP_CONTROLLER             0x2000
#define MODBUS_ADDRESS_DAY_NIGHT                        0x200C

